### ISSUE TITLE
Create BrandCentral Connector add-on

### ISSUE THREAD

**Issue by aembler** [concrete5/brand_central#41]
In https://github.com/concrete5/brand_central/issues/40 I describe a new add-on, installable via composer, that can be included in any concrete5 site. This is a standard concrete5 package that, when installed, adds a new link to the file chooser. This link is actually a kind of file uploader that lets you choose assets from third party sites. Clicking on those assets imports the files into your local file manager.

I have created the repository for this here:

https://github.com/concrete5/brand_central_connector

Create the basic package in this location, make sure it can be installed via composer. It should give you a dashboard settings page that lets you specify API key and secret (which will be generated within the API dashboard settings page of the BrandCentral site you're trying to connect to.) It will also add a series of predefined routes that our external file provider vue component will search, on our local site. These will use a PHP API to connect to the external brandcentral site. In a sense the connector is an API proxy for the external site.

**Comment by aembler** [comment]
Also, as part of this, let's create a new file attribute. Its handle is `brand_central_asset_file_id`. Any time the custom brand central asset is imported into concrete5, let's assign this file attribute to the imported ID, so we can map the local file that's copied from brandcentral to the central record. We don't need to do any more than just save this attribute against the imported file, this is just in case we want to do something with this data later.

**Comment by aembler** [comment]
Fabian,

This is looking great! There are some small things but I think you can probably get most of those dialed in today/tonight, and we'll be in a good spot for a demo later this week and to deliver it to the client next week. Really coming together nicely. Good work.

I'm not going to group these necessarily by type... so some of them will be in the core and some fo them will be in the connector add-on, it's mostly going to be grouped based on the order that I came into contact with the issues.

1. After I've added an external file provider, I don't see an icon next to it on the dashboard page. A quick look shows that this is using fa-hdd (which is probably a hold over from the storage location types dashboard page. Can you change this so that it's using `fas fa-file-export` ? That will probably help it show up properly.

2. On the add/edit form for an External File Provider, can you change the label "Endpoint" to read "BrandCentral Site URL" and a div with the class "help-block" beneath it that says 

"Enter the URL of your BrandCentral site, with a trailing slash. For example: https://www.mybrandcentralsite.com/"

3. Beneath Client Id and Client Secret can you add another div with the class "help-block" that says "Generate a client ID and a Client Secret from the API Settings page in your BrandCentral page. Copy the generated values from that external site and paste them into here."

4. When you go into the file picker from the frontend, I noticed that there's a little bit of lag, which makes sense since you have to communicate with BrandCentral over the API. However, is there any possible way that we can make that communication ONLY happen if you click the BrandCentral tab in the picker? For example, I simulated some BrandCentral downtime by turning off my BrandCentral site after I installed and configured the connector, and then I went to my file picker, and this is what I got right away:

![image](https://user-images.githubusercontent.com/527809/96631724-8ab96900-12cb-11eb-96a6-167ac7e3e831.png)

I know this is probably difficult given the way these components are built, and if it's going to be harder it's something we can put on hold until later this week/early next week, but I don't want an outage on BrandCentral to make it so that no site hooked into it is able to use any of the file pickers in any of the blocks on their own site.

5. Let's change "Please select" in the BrandCentral search interface to "** Select All" and make sure it works to search all assets.

6. I clicked the BrandCentral and attempted to search just photos with no keywords, and it didn't work. I can understand the technical potential issues with this, but if we're not going to allow this, let's make the keywords field required using the required="required" dom attribute, and let's disable the search icon unless there are keywords

7. Let's get rid of the "minimum 3 character" search requirement here. We don't really do that anywhere else.

8. None of my thumbnails are showing up. Additionally on the "choose asset to import" dialog none of the images are showing up there either. 

This is looking great! I didn't have any oauth2 issues so that must be something that's environment specific. 

I might be able to find some other small things but nothing that would hold up getting this merged into the core. Let me know when these small things are resolved and I'll accept your pull requests for brand central, the connector and the core, and we'll move on to the next tasks. Thanks again

**Comment by bitterdev** [comment]
Hi Andrew,

i have implemented all change requests. You need to update all repositories (c5, bedrock, brand_central + connector).

Point 8 is the only one that is "unfixed". Please can you check the network traffic in your console? I assume that this is a CORS related issue. You need to whitelist the client sites. Or if you want you can allow all origins, see:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

You can just add this to a .htaccess file. 

Notice: If you use the drop box add-on and integrate a S3 storage you need to configure the CORS rules of the S3 endpoints also.

Other options are:
1) Adding the CORS rules in a middleware with PHP
2) Creating a Proxy Path that is downloading the file temporary on server-side on returning the data on client side. But this has speed issues and depending on the implementation this can be a security risk. 

As soon as this task is approved/finished i will start the tasks #9129 (fav folder) + #9130 (home folder) on concrete5.

**Comment by aembler** [comment]
Completed!
